### ISSUE TITLE
lightbulb/facilitator v2

### ISSUE THREAD

**Issue by gdykeman** [ansible/lightbulb#106]
Introduction to Ansible Tower Hands-On Workshop

Believe the prerequisites content is for non 'hands-on' workshops.  Might need to have similar wording to the Ansible Hands-On workshop.  Currently, it looks like it's worded to be a lecture / non hands-on.

**Comment by tima** [comment]
The two Tower workshops are placeholders taken from a previous generation of material.

**Comment by gdykeman** [comment]
Roger. Closing.
