### ISSUE TITLE
Configure firewalld will all ports needed for lab exercise and workshops rather than stop it

### ISSUE THREAD

**Issue by tima** [ansible/lightbulb#117]
Thinking ports 22, 80, 443, 8080, 8888. Currently firewalld (RHEL7) blocks everything but port 22. Others?

**Comment by jlozadad** [comment]
this can be closed.

**Comment by samdoran** [comment]
Wasn't sure if we wanted to add more ports or not.

**Comment by tima** [comment]
Well I wanted to add 8080 and 8888 for once  #92 gets worked in, but closing this is fine for now.
