### ISSUE TITLE
Cleanup inline CSS styles and abstract to ansible.css file

### ISSUE THREAD

**Issue by tima** [ansible/lightbulb#119]

**Comment by jvanpelt** [comment]
Fixed [here](https://github.com/ansible/lightbulb/commit/301054549b9ff13ceb2f6ccafbfec797638de968)

**Comment by tima** [comment]
Thanks @jvanpelt. I'm going to close this. I have other things I'd liked to improve around the print stylesheet and making the presentation slides more reactive. I have had some issues with different (especially high) resolutions not looking quite right. I will file new issues once I can write something more specific down though.
