### ISSUE TITLE
[WARNING]: Found both group and host with same name: control

### ISSUE THREAD

**Issue by gdykeman** [ansible/lightbulb#130]
tools/aws_lab_setup/roles/manage_ec2_instance/templates/instances.txt.j2

Looks like the inventory format was changed to have control in the control group.  Might want to change the group to tower or something other than control to prevent the warning.  Although it's not a critical issue that prevents the workshop, might be better to not have it pop up.

**Comment by tima** [comment]
What version of Ansible are you running? Or was this Tower?

**Comment by kyleabenson** [comment]
This might have been discussed/clarified already, but I get the same notice. 

Having the provisioner change the host alias to something like node-control to follow the node-[1:3] schema would get rid of this notice.

Using running from the cli with the following settings:

[kbenson@control ~]$ ansible --version
ansible 2.3.1.0
  config file = /home/kbenson/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

This occurs whenever using the supplied/generated inventory,  simply to notify that if you specify 'control' that there is both a group and host alias with that name.

**Comment by tima** [comment]
Yeah this probably wasn't the best choice even when it was made way back when. We should probably rename the node "ansible" (not all forms use Tower) and leave the group as "control". I think that should cause the least amount of disruption. 

Thoughts? Someone want to put together a PR?
