### ISSUE TITLE
Fix aggressive wrapping of lists in presentation decks. 

### ISSUE THREAD

**Issue by tima** [ansible/lightbulb#131]
The styling of bullet point lists (particularly the Tower deck) aggressively wrap longer lines and leave a lot of whitespace on the page unused. See screenshot below:

<img width="993" alt="screen shot 2017-05-08 at 4 46 08 pm" src="https://cloud.githubusercontent.com/assets/50353/25824813/9a127f26-340e-11e7-9850-e484ad6a581d.png">
----
<img width="1087" alt="screen shot 2017-04-24 at 1 39 55 pm" src="https://cloud.githubusercontent.com/assets/50353/25824814/9a446a7c-340e-11e7-8aab-1c663b5a1aaf.png">

**Comment by jvanpelt** [comment]
I've committed a fix for this issue.

**Comment by tima** [comment]
This seems fixed. Closing.
