### ISSUE TITLE
Ansible Tower Basic Setup Solution doc is a "work in progress."

### ISSUE THREAD

**Issue by tima** [ansible/lightbulb#165]
The solution to the Ansible Tower Basic Setup workshop, `facilitator/solutions/tower_basic_setup.md`, is incomplete. 

For instance, it's missing explanatory and contextual text around the screenshots. It also seems to be missing steps at the end or anything for the extra credit assignment. 

Also, one if the screenshots (1b) is appears broken when the markdown is rendered.

**Comment by thedoubl3j** [comment]
taking a look now. should have a PR sometime soon.

**Comment by thedoubl3j** [comment]
PR open in regards to this issue and it can be found here. https://github.com/ansible/lightbulb/pull/179

**Comment by tima** [comment]
Closing. Addressed by PR #179.
