### ISSUE TITLE
The Ansible community RPM package will transition from the EPEL repository to the Extras channel

### ISSUE THREAD

**Issue by gdykeman** [ansible/lightbulb#202]
Need to enable rhel-7-server-extras-rpms to install ansible during provisioning.
Which also means... that we need to subscribe the boxes too...

**Comment by tima** [comment]
Related to #85/#151 meaning we could get around this problems by switching back to pip.

**Comment by tima** [comment]
Thanks @gdykeman. I did a cherry-pick of the commit that contained this fix. It also had a change to the inventory path on the controller. Hope that was intentional.

**Comment by gdykeman** [comment]
@tima Ty! Change to inventory path was intentional as there is a current
bug with reading a directory for the inventory rather than full path to a
specific inventory file.
