### ISSUE TITLE
boto3 required for running 

### ISSUE THREAD

**Issue by nicholas-chia** [ansible/lightbulb#204]
ansible engine v2.4
rhel7.4

boto3 required. Just do a pip install boto3 to resolve issue.

The full traceback is:
  File "/tmp/ansible_hveeDb/ansible_module_ec2_group.py", line 279, in <module>
    import botocore

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "description": "all ports open", 
            "ec2_url": null, 
            "group_id": null, 
            "name": "insecure_all", 
            "profile": null, 
            "purge_rules": true, 
            "purge_rules_egress": true, 
            "purge_tags": true, 
            "region": "us-west-1", 
            "rules": [
                {
                    "cidr_ip": "0.0.0.0/0", 
                    "proto": "all"
                }
            ], 
            "rules_egress": [
                {
                    "cidr_ip": "0.0.0.0/0", 
                    "proto": "all"
                }
            ], 
            "security_token": null, 
            "state": "present", 
            "tags": null, 
            "validate_certs": true, 
            "vpc_id": "vpc-b4b774d0"
        }
    }, 
    "msg": "boto3 required for this module"
}

**Comment by tima** [comment]
OK. I suppose this is an omission of the docs. Without checking I'm going to guess the ec2_group module was modified to use the new client library as opposed to the legacy one. Will be thru a PR shortly.
