### ISSUE TITLE
Review Merge Pull Request 228

### ISSUE THREAD

**Issue by IPvSean** [ansible/lightbulb#229]
Need another setup of eyes on 227/228 Pull request.  This automates build-up of a topology for the instructor-led workshop on AWS.  However if you are manually creating key-pairs and VPCs you can still over-ride it (meaning if you are using current lightbulb, there is no difference to behavior today).  Would love someone to test this out.
https://github.com/ansible/lightbulb/pull/228

**Comment by tima** [comment]
Noted. Will track the need to do this thru the PR.
