### ISSUE TITLE
slide navigation changes on slide 43 in ansible-essentials.html

### ISSUE THREAD

**Issue by dswhitley** [ansible/lightbulb#233]
Prior to the "Doing More with Playbooks" slide (43), most slides are progressed logically to the right.  However, in order to view the slides associated with this section, the presenter must navigate "down".

If this is not by design, I believe it is due to an extra `<section>` on line 892:  https://github.com/ansible/lightbulb/blob/10fa443916396445f0c9044208951349772a1f06/decks/ansible-essentials.html#L892

**Comment by tima** [comment]
It's by design.
