### ISSUE TITLE
wrong link in aws_lab_setup README

### ISSUE THREAD

**Issue by dswhitley** [ansible/lightbulb#242]
The [aws_lab_setup](https://github.com/ansible/lightbulb/blob/master/tools/aws_lab_setup/README.md) README.md file, in step 3, reads "Access Key ID and Secret Access Key" yet the link directs to http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSGettingStartedGuide/AWSCredentials.html which does not match the wording.

**Comment by dswhitley** [comment]
If **NOT** using IAM, then should the link point here:  http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html

However, that page recommends using IAM, and that link would be:  http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html

**Comment by tima** [comment]
Fixed by #245
