### ISSUE TITLE
Serve decks via gh-pages

### ISSUE THREAD

**Issue by webknjaz** [ansible/lightbulb#258]
Hi,

It might be a good idea to host slides online. One way of doing this is to push html/static contents to gh-pages and let GitHub serve the static.

This can be automated using [Pages Deployment Provider @ Travis](https://docs.travis-ci.com/user/deployment/pages/).

Plz let me know if you'd like to have some help with this.

**Comment by IPvSean** [comment]
We are in the process of doing this already.  You can actually see my setup of this hosted on https://ansible.com/net-lightbulb

**Comment by webknjaz** [comment]
Would you please refer it in README?

**Comment by thedoubl3j** [comment]
most definitely @webknjaz

**Comment by tima** [comment]
This is a duplicate of #220 and as already noted this is under way with @jvanpelt leading that for us.
