### ISSUE TITLE
Broken link in guides

### ISSUE THREAD

**Issue by webknjaz** [ansible/lightbulb#284]
In [this readme](https://github.com/ansible/lightbulb/tree/master/guides/ansible_engine#ansible-engine-exercises) link to `Exercise 4 - Roles: Making your playbooks reusable` points to non-existing folder `4-roles`, while the correct name is `4-role`.

Same errors are present at https://network-automation.github.io/lightbulb/workshops/ansible_engine/:
- `https://network-automation.github.io/lightbulb/workshops/ansible_engine/4-runplaybook ` contains trailing space
- `https://network-automation.github.io/lightbulb/workshops/ansible_engine/5-roles` contains trailing `s`

**Comment by tima** [comment]
Thanks @webknjaz. We'll look into correcting that or feel free to submit a PR yourself that references this issue.
