### ISSUE TITLE
Drop wsgi from nginx-basic-playbook example

### ISSUE THREAD

**Issue by webknjaz** [ansible/lightbulb#287]
This example shows how to set up a web-server serving static, it does nothing with WSGI (except for installing `uwsgi`, which doesn't make sense)

Ref: https://github.com/ansible/lightbulb/blame/master/examples/nginx-basic-playbook/site.yml#L3

**Comment by tima** [comment]
True, but it was there to show a loop and for future use in content we've not gotten around to developing. That example is the solution to one of the hands-on `workshops` also.
