### ISSUE TITLE
Outdated Tower screenshots

### ISSUE THREAD

**Issue by webknjaz** [ansible/lightbulb#290]
* [ ] slide "Schedule Jobs"
* [ ] https://github.com/ansible/lightbulb/tree/master/guides/ansible_tower/3-create#step-5-1
* [ ] also, some pictures in guides are missing from the repo completely

**Comment by tima** [comment]
Thanks for reporting this @webknjaz. Can you be more specific to which images are missing entirely in your third point?

**Comment by webknjaz** [comment]
https://github.com/ansible/lightbulb/blob/master/guides/ansible_tower/README.md - tower logo
https://github.com/ansible/lightbulb/tree/master/guides/ansible_tower/2-config#step-5 - submit button, add button, create an inventory

**Comment by thedoubl3j** [comment]
will take a look at this tomorrow and into next week. apologies on being late

**Comment by liquidat** [comment]
@webknjaz, thanks for pointing those out, great work! I think I've fixed most of them :)
But I don't find the first one actually:

>  slide "Schedule Jobs"

Do you mean [the one in the decks](https://github.com/ansible/lightbulb/blob/master/decks/images/tower/schedule-jobs.png)? That looks right to me, what do you think is wrong with that one?

**Comment by webknjaz** [comment]
I guess. Honestly, I don't remember now, but looks like it.
As I recall, it looked differently from what I saw in my installation of Tower.

**Comment by liquidat** [comment]
@webknjaz Thanks for the quick answer. I checked, and it mostly looks like my local installation, so I suggest we will keep it for now.
The rest should be closed by PR #309 , so I'd say we can close this issue.
