### ISSUE TITLE
Incorrect link in workshops/basic_playbook

### ISSUE THREAD

**Issue by ayushkalani** [ansible/lightbulb#300]
The uri_module link in `https://github.com/ansible/lightbulb/tree/master/workshops/basic_playbook` to uri_module is pointing to template_module.
There is a mismatch in link, I have corrected the link and now it's pointing to uri_module i.e-
http://docs.ansible.com/ansible/latest/modules/uri_module.html

**Comment by tima** [comment]
Closed by #301
