### ISSUE TITLE
Switch back to EPEL again

### ISSUE THREAD

**Issue by tima** [ansible/lightbulb#310]
Back by popular demand, Ansible is back in EPEL and is the preferred way for the community using Lightbulb to install it.

We need to reverse this commit: 5def529e5c4ee04d19138f715ed9a0bb5f6c09c4 and scan the guide, speaker notes and workshops to make sure they are consistent and reflect the use of EPEL.

**Comment by liquidat** [comment]
@tima 

> is the preferred way for the community using Lightbulb to install it
So is EPEL the preferred way - of pip? Because in most cases (decks, etc.) we recommend pip and not the RPM way of installing Ansible.

**Comment by tima** [comment]
Yes @liquidat: yum as opposed to pip installation is necessary in the context of lightbulb. That should have been fixed some months ago. The problem is if you install engine using pip you will run into all sorts of problems when you try to install Tower.
