### ISSUE TITLE
Failed to get: undefined GET returned: 401 Authentication credentials were not provided.

### ISSUE THREAD

**Issue by nicholas-chia** [ansible/lightbulb#311]
Been getting 401 errors on Tower UI during Lightbulb sessions. Logout of UI and added the below line into /etc/tower/settings.py helped.

REMOTE_HOST_HEADERS = ['HTTP_X_FORWARDED_FOR']

This was reported in AWX https://github.com/ansible/awx/issues/1019

**Comment by tima** [comment]
Interesting. @dfederlein is this something you and your team have come across and remedied?

**Comment by nicholas-chia** [comment]
I have a workshop today again and I have to add the same settings and restart tower service. All the students are seeing the same error.

**Comment by thedoubl3j** [comment]
will take a look into it. haven't seen this recently but I will check our ticket log and see if we have addressed this.

**Comment by thedoubl3j** [comment]
@nicholas-chia are you running in aws either behind an ELB or proxy? or running locally behind an LB/proxy?

**Comment by dfederlein** [comment]
I'll pull this branch and stand up to test myself.

@nicholas-chia can you tell me what region you're launching in?

**Comment by nicholas-chia** [comment]
@thedoubl3j hosted on AWS. Standard provisioning. No ELB or Proxy configured. But if there was a transparent proxy configured in the network I was in, that could explain why I am seeing this. I will test again in Singapore when I get back.

@dfederlein the region is ap-southeast-1 (Singapore).

**Comment by thedoubl3j** [comment]
sounds good @nicholas-chia that was my first thought, if there is nothing there let us know and we dive deeper.

**Comment by dfederlein** [comment]
I wonder if the place you were giving the demo/workshop had a proxy for all network traffic out to web...

I can't replicate this one.

**Comment by nicholas-chia** [comment]
Did not get any issues in Singapore. I think it's likely the transparent proxy at the premises I last ran the workshop. Gonna close this. Thanks.
