### ISSUE TITLE
remove "who am I" slide from best-practises deck?

### ISSUE THREAD

**Issue by rndmh3ro** [ansible/lightbulb#342]
When using the best-practices deck for my own presentations as a teacher, the "Who am I" slide is misleading as that's not me. :)

Any reason, it is in there? If not, I can make a PR to remove it.

**Comment by gundalow** [comment]
Oh, I left that in, my mistake, I'll replace it with a template.

**Comment by rndmh3ro** [comment]
Fixed by https://github.com/ansible/lightbulb/pull/343, thanks!
