### ISSUE TITLE
Remove sendgrid module from aws_lab_setup once tested on v2.0. 

### ISSUE THREAD

**Issue by tima** [ansible/lightbulb#54]

**Comment by samdoran** [comment]
This is merged into 2.2. I'll remove the built-in module once 2.2 ships.

**Comment by samdoran** [comment]
Removed custom sendgrid module in https://github.com/ansible/lightbulb/pull/81/commits/60dabb213db41fe0415bfd2a66a8572e5980dd6f. Tested with Ansible 2.2.0.0 and seems to work. Can others test to verify?

**Comment by tima** [comment]
I can verify with the caveat of #70. Closing.
