### ISSUE TITLE
Tower 3.0.1 fails to install on control machine

### ISSUE THREAD

**Issue by smapjb** [ansible/lightbulb#73]
The control machine is set up with epel-release installed..

The tower installer writes its own epel repo file called epel-7 and so the ./setup.sh fails because of a duplicate EPEL repo.

Fundamentally I think this is a problem with the tower installer. But to resolve this I did a 
`yum erase epel-release`

**Comment by samdoran** [comment]
@smapjb I run into this all the time as well. This is an issue with the Ansible Tower installer. I'll submit a PR to ansible-tower to make the installer more intelligent.

**Comment by samdoran** [comment]
From talking with @ghjm more today, seems this is more an issue with using PIP to install Ansible. I'm going to shift gears and try installing Ansible via yum and see if we still run into issues.

**Comment by samdoran** [comment]
Think I've gotten to the bottom of this and have a working solution.

As @ghjm pointed out, removing `epel-release` _doesn't_ actually fix the problem — that was a red herring. Running `setup.sh` _twice_ is what does the trick for reasons I didn't bother to determine.

The fix is to install Ansible via `yum` not `pip`. I'll submit a PR shortly.

**Comment by tima** [comment]
For the sake of getting a Tower instance up quickly and usable, would it be better to use the prebuilt Tower AMIs etc here? Just a thought.

**Comment by samdoran** [comment]
It depends. If we want to teach Tower installation as part of the training, then nope. But if the goal is to teach Tower, installing it may or may not be valuable but getting into Tower faster is more valuable. Probably should ask @thisdavejohnson and @wtcross.

**Comment by tima** [comment]
@samdoran For what we've been talking it's both unfortunately.

**Comment by samdoran** [comment]
Fixed Tower installation falirue in e5a1fc03fad8de930c2c777fe04336babbeb31ee.

**Comment by tima** [comment]
@sdoran: Can this be closed?

**Comment by samdoran** [comment]
@tima The fix for this is in #81. Need to get that merged in order to close this.
