### ISSUE TITLE
Split AMIs data out from AWS instance size and disk information

### ISSUE THREAD

**Issue by tima** [ansible/lightbulb#82]
[This comment refers to the refactored lab provisioner being developed in #81.]

Since AMIs are only available in one region and we want to support different operating systems (RHEL and CentOS to start), AMIs meta data should be separate from the instance sizing and lab topology definition. The OS type can be static.

Which regions to support initially needs to be determined. Prior to this, lightbulb has only traditionally used us-east-1.

**Comment by samdoran** [comment]
Added this in b00054a5e4d7e186699014a786918c1d7bc78850

**Comment by tima** [comment]
Looks like this can be closed now.
