### ISSUE TITLE
install pip and install ansible with it

### ISSUE THREAD

**Issue by tima** [ansible/lightbulb#85]
[This comment refers to the refactored lab provisioner being developed in #81.]

Some forms of hands on training use pip in their exercises to install python dependencies. The provisioner used to install pip, but was changed(?) to use yum exclusively.

Installing using PIP is the recommend/preferred means of installing ansible. Not using pip can be problematic because of the occasional lag new releases see getting into other channels that PyPi does not suffer from.

**Comment by samdoran** [comment]
Ansible installation was switched to `yum` to fix the problem in issue #73. Switching back to using `pip` needs to be tested more.

**Comment by tima** [comment]
As noted in #151, installing with pip causes problems if you are going to install Tower later on the same box. Closing this out.
