### ISSUE TITLE
apache_dirs undefined

### ISSUE THREAD

**Issue by heenashree** [ansible/lightbulb#89]
I am getting below error while executing playbook for apache
{"failed": true, "msg": "'apache_dirs' is undefined"}
so I defined apache_dirs: /etc/httpd in webservers under group_vars folder but the issue remains.

**Comment by tima** [comment]
@heenashree: Can you be specific as to which playbook (file path) and branch you got this with? We have a few apache playbooks floating around as part of the progressive build up of concepts.

**Comment by heenashree** [comment]
I am using below playbook lightbulb/lessons/apache_centos_ubuntu/roles/apache/tasks/main.yml

Running ansible-playbook gives same error for lameversion as well even though it has been specified in group_vars



FAILED! => {"failed": true, "msg": "the field 'args' h       as an invalid value, which appears to include a variable that is undefined. The        error was: 'lameapp_version' is undefined\n\nThe error appears to have been in '       /etc/ansible/roles/web/tasks/main.yml': line 7, column 3, but may\nbe elsewhere        in the file depending on the exact syntax problem.\n\nThe offending line appears        to be:\n\n\n- name: checkout lameapp\n  ^ here\n"}

**Comment by tima** [comment]
Thanks for the report. With the "v2" release of lightbulb this example has been retired and removed from the repo. Closing this out.
