### ISSUE TITLE
Tower lab license

### ISSUE THREAD

**Issue by tima** [ansible/lightbulb#90]
We need to document and/or automate licenses to run Tower in a lab environments.

**Comment by gdykeman** [comment]
Currently uploading to S3 (a day or so prior to the workshop) and have the students reference it during the workshop.

**Comment by tima** [comment]
Each student should apply for a 5-day 5-node trial license here: https://www.ansible.com/workshop-license. License files is delivered to their inbox usually in 1 to 2 minutes.
