### ISSUE TITLE
Apache to Nginx transition (need to stop service)

### ISSUE THREAD

**Issue by gdykeman** [ansible/lightbulb#94]
If running through the examples in order, students will error on nginx examples as the http port is busy.  Need to include a playbook to stop httpd and or have the students perform that before moving onto nginx.

**Comment by tima** [comment]
Agreed. This could also be addressed by #92 and using a different port with nginx examples. Would need to check the provisioner has created a security group with that port open.

**Comment by tima** [comment]
I've written the basic playbook and roles workshops with extra credit assignments to create a stop and remove playbook/tasks. Need to provide the solution in the nginx examples at a minimum.

**Comment by tima** [comment]
Implemented with 0db28a8.
